package io.github.gubarsergey.stratosphericbaloon.helper

import java.util.*

object DatabaseKeyConverter {

    /**
     * Converts string generated by Arrays.toByteArray() to ByteArray
     * @param key - string in format "[1, 2, 3]"
     */
    fun keyToByteArray(key: String): ByteArray {
        return key.drop(1).dropLast(1).split(",").map { it.trim().toByte() }.toByteArray()
    }

    fun keyToString(key: ByteArray): String {
        return Arrays.toString(key)
    }
}